### ISSUE TITLE
Add import example for require()

### ISSUE THREAD

**Issue by shawntax** [xyfir/rword#4]
Firstly, thank you for your work in creating this package. It's really cool!

Is there any plan to make `rword` compatible with CommonJS, or will it only be available as a ES module?

**Comment by MrXyfir** [comment]
What troubles exactly are you having with it? It should work without ES modules as far I'm aware.

**Comment by shawntax** [comment]
Sorry--should have given more detail.

I'm  requiring `rword` as a CommonJS module:

```const rword = require('rword')```

and when I use the `generate` method:

```  const words = rword.generate(4, { length: '3-5' });```

I'm running into  a `TypeError: rword.generate is not a function`.

My guess was that since the README only describes using `rword` as an ES Module (`import { rword } from 'rword';`), this had something to do with CommonJS module support? When I run my script importing `rword` as an ES module with [esm](https://github.com/standard-things/esm]), it works fine.

Here's a quick stack trace:

```
Trace: TypeError: rword.generate is not a function
    at generatePassword (/Users/staxerman/de/create-users/create-users.js:12:23)
    at Object.<anonymous> (/Users/staxerman/de/create-users/create-users.js:18:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
    at Object.<anonymous> (/Users/staxerman/de/create-users/create-users.js:33:11)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
```

I'm on node `v12.1.0`

**Comment by MrXyfir** [comment]
Ah, I see.

Lucky for you, this is a simple solution!

```js
const { rword } = require('rword');
console.log(rword.generate());
```

I should probably document that better.

**Comment by shawntax** [comment]
I'm an idiot 🤦Thanks for pointing that out!

I'm sure extra documentation on it wouldn't hurt :)
